### ISSUE TITLE
تحديد أهداف قابلة للقياس و التحقيق للمشروع

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/AIUX#3]
<div dir="rtl" align="right">

عشان نقدر ننفذ أي حاجة محتاجين مجموعة أهداف تتحدد و يتعمل طرق قياس نجاح كل هدف و خطط لتنفيذ الأهداف دي. 
من ضمن الأهداف اللي جت فبالي هما:

   
-  تقديم محتوى عربي
-  نفخر به
- رفع مستوى جودة المحتوى العربي الموجود
- زيادة التوعية عن وجوب وجود محتوى عربي ذو جودة عالية
- تطوير تقنيات مساعدة أو إعادة تدوير تقنيات موجودة مسبقاً في جهود موّحدة
- زيادة التوعية و جودة التعليم للإهتمام بالتقنيات المساعدة

هل الأهداف دي واضحة كفاية او محتاجة تعديلات؟

</div>

**Comment by yasminevt** [comment]
‎اقترح اعادة صياغة الأهداف العامة و اضافة أهداف فرعية لاحقا
‎١- الترجمة من اللغات الأجنبية الى اللغة العربية 
‎٢- تطوير الأدوات المساعدة Assistive technology لخدمة المستخدمين العرب
‎٣- اتباع معايير الaccessibilityإتاحة عند صناعة برمجيات أو محتوى عربي
‎٤- تعليم المطورين و الطلاب قواعد و معايير انشاء برمجيات متاحة للجميع accessible

**Comment by KL13NT** [comment]
<div dir="rtl">

> 
> 
> ‎اقترح اعادة صياغة الأهداف العامة و اضافة أهداف فرعية لاحقا
> ‎١- الترجمة من اللغات الأجنبية الى اللغة العربية
> ‎٢- تطوير الأدوات المساعدة Assistive technology لخدمة المستخدمين العرب
> ‎٣- اتباع معايير الaccessibilityإتاحة عند صناعة برمجيات أو محتوى عربي
> ‎٤- تعليم المطورين و الطلاب قواعد و معايير انشاء برمجيات متاحة للجميع accessible

دي بالفعل صياغة افضل من الموجودة :smiley: هغير الاهداف اللي محطوطة دلوقتي

تقترحي ايه لقياس نجاح الأهداف دي؟ 

</div>
