### ISSUE TITLE
ترجمة الوثائق الموجودة (README)

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/AIUX#8]
<div dir="rtl">

من الواضح اننا هنحتاج نترجم المقدمات اللي موجودة هنا عشان بدأ يدخل موضوع زي اضافة دعم للغة العربية في الادوات المختلفه و ده بيدخل فيه اجانب و بيتعمل ربط للريبو دي في اماكن مختلفه. عشان كده لازم نترجم المحتوى اللي هنا (على الاقل المقدمة) علشان يوصل هدف الموضوع كله لغير العرب. 

ده تعديل اي حد بخبرة جيدة في اللغة يقدر ياخدها, هسيب الـ issue مفتوحة فترة لأي حد حابب ياخدها. ابقوا قولوا بس عشان ميبقاش في كذا حد شغال عليها ف نفس الوقت. 

</div>

**Comment by Adamkaram** [comment]
وصلت لحاجه ؟

**Comment by KL13NT** [comment]
@Adamkaram 

تم ترجمة الوثائق كلها.
